//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{ 
    public enum ColliderType
    {
        /// <summary>
        /// 固定位置碰撞体
        /// </summary>
        FixedPosition = 0,
        /// <summary>
        /// 固定方向碰撞体
        /// </summary>
        FixedRotation = 1,
        /// <summary>
        /// 朝指定位置方向飞行碰撞体
        /// </summary>
        Target = 2,
        /// <summary>
        /// 锁定目标飞行
        /// </summary>
        Aim = 3,
        /// <summary>
        /// 立刻结算
        /// </summary>
        Immediate = 4,
    }

} 
