//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class FormulaConfig: Bright.Config.BeanBase
{
    public FormulaConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Formula = _buf.ReadString();
        PostInit();
    }

    public static FormulaConfig DeserializeFormulaConfig(ByteBuf _buf)
    {
        return new FormulaConfig(_buf);
    }

    /// <summary>
    /// 一个数值可能会多种情况影响，比如速度,加个buff可能增加速度绝对值100，也有些buff增加10%速度，所以一个值可以由5个值进行控制其最终结果
    /// </summary>
    public int Id { get; private set; }
    public string Formula { get; private set; }

    public const int __ID__ = -115487704;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Formula:" + Formula + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}