//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class SkillStepData: Bright.Config.BeanBase
{
    public SkillStepData(ByteBuf _buf) 
    {
        TriggerTime = _buf.ReadInt();
        StepStyle = (SkillStepType)_buf.ReadInt();
        {int __n0 = System.Math.Min(_buf.ReadSize(), _buf.Size);StepParameter = new string[__n0];for(var __index0 = 0 ; __index0 < __n0 ; __index0++) { string __e0;__e0 = _buf.ReadString(); StepParameter[__index0] = __e0;}}
        PostInit();
    }

    public static SkillStepData DeserializeSkillStepData(ByteBuf _buf)
    {
        return new SkillStepData(_buf);
    }

    /// <summary>
    /// 时间节点
    /// </summary>
    public int TriggerTime { get; private set; }
    /// <summary>
    /// 步骤类型
    /// </summary>
    public SkillStepType StepStyle { get; private set; }
    /// <summary>
    /// 步骤参数
    /// </summary>
    public string[] StepParameter { get; private set; }

    public const int __ID__ = -1839488537;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "TriggerTime:" + TriggerTime + ","
        + "StepStyle:" + StepStyle + ","
        + "StepParameter:" + Bright.Common.StringUtil.CollectionToString(StepParameter) + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}