//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;

namespace ET
{
   
[Config]
public partial class SkillEffectsConfigCategory: ConfigSingleton<SkillEffectsConfigCategory>
{
    private readonly Dictionary<int, SkillEffectsConfig> _dataMap;
    private readonly List<SkillEffectsConfig> _dataList;
    
    public SkillEffectsConfigCategory(ByteBuf _buf)
    {
        _dataMap = new Dictionary<int, SkillEffectsConfig>();
        _dataList = new List<SkillEffectsConfig>();
        
        for(int n = _buf.ReadSize() ; n > 0 ; --n)
        {
            SkillEffectsConfig _v;
            _v = SkillEffectsConfig.DeserializeSkillEffectsConfig(_buf);
            _dataList.Add(_v);
            _dataMap.Add(_v.Id, _v);
        }
        PostInit();
    }
    
    public bool Contain(int id)
    {
        return _dataMap.ContainsKey(id);
    }

    public Dictionary<int, SkillEffectsConfig> GetAll()
    {
        return _dataMap;
    }
    
    public List<SkillEffectsConfig> DataList => _dataList;

    public SkillEffectsConfig GetOrDefault(int key) => _dataMap.TryGetValue(key, out var v) ? v : null;
    public SkillEffectsConfig Get(int key) => _dataMap[key];
    public SkillEffectsConfig this[int key] => _dataMap[key];

    public override void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        foreach(var v in _dataList)
        {
            v.Resolve(_tables);
        }
        PostResolve();
    }

    public override void TranslateText(System.Func<string, string, string> translator)
    {
        foreach(var v in _dataList)
        {
            v.TranslateText(translator);
        }
    }
    
    public override void TrimExcess()
    {
        _dataMap.TrimExcess();
        _dataList.TrimExcess();
    }
    
    
    public override string ConfigName()
    {
        return typeof(SkillEffectsConfig).Name;
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}