//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{ 
    public enum StartPosType
    {
        /// <summary>
        /// 1自身
        /// </summary>
        Self = 1,
        /// <summary>
        /// 2目标
        /// </summary>
        Aim = 2,
        /// <summary>
        /// 3鼠标位置
        /// </summary>
        MousePos = 3,
    }

} 
