//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class ChildStatusConfig: Bright.Config.BeanBase
{
    public ChildStatusConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        ID = _buf.ReadString();
        ChildStatus1 = _buf.ReadString();
        Status1KV1 = _buf.ReadString();
        Status1KV2 = _buf.ReadString();
        ChildStatus2 = _buf.ReadString();
        Status2KV1 = _buf.ReadString();
        Status2KV2 = _buf.ReadString();
        PostInit();
    }

    public static ChildStatusConfig DeserializeChildStatusConfig(ByteBuf _buf)
    {
        return new ChildStatusConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 状态ID
    /// </summary>
    public string ID { get; private set; }
    public string ChildStatus1 { get; private set; }
    public string Status1KV1 { get; private set; }
    public string Status1KV2 { get; private set; }
    public string ChildStatus2 { get; private set; }
    public string Status2KV1 { get; private set; }
    public string Status2KV2 { get; private set; }

    public const int __ID__ = 2055192816;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "ID:" + ID + ","
        + "ChildStatus1:" + ChildStatus1 + ","
        + "Status1KV1:" + Status1KV1 + ","
        + "Status1KV2:" + Status1KV2 + ","
        + "ChildStatus2:" + ChildStatus2 + ","
        + "Status2KV1:" + Status2KV1 + ","
        + "Status2KV2:" + Status2KV2 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}