//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{ 
    public enum SkillStepType
    {
        /// <summary>
        /// 空
        /// </summary>
        None = -1,
        /// <summary>
        /// 仅等待
        /// </summary>
        Wait = 0,
        /// <summary>
        /// 改变坐标<br/>参数1:相对坐标字符串&quot;x,y,z&quot;
        /// </summary>
        Move = 1,
        /// <summary>
        /// 播动画<br/>参数1:动画名
        /// </summary>
        Anim = 2,
        /// <summary>
        /// 播放声音<br/>参数1:音频路径
        /// </summary>
        Sound = 3,
        /// <summary>
        /// 结算消耗<br/>参数1:消耗的属性Key字符串,<br/>参数2:固定消耗值,<br/>参数3:消耗的计算公式
        /// </summary>
        Cost = 4,
        /// <summary>
        /// 生成召唤物<br/>参数1:召唤物Id
        /// </summary>
        GenerateObject = 5,
        /// <summary>
        /// 生成碰撞器<br/>参数1:触发器Id(整数),<br/>参数2:伤害计算公式Id(整数),<br/>参数3:最终伤害百分比(0-1小数),<br/>参数4:最大作用单位数(0表示无限)(整数),<br/>参数5:&quot;buff1,buff1持续时间单位毫秒,buff1离开范围是否移除buff0或1;buff2,buff2持续时间单位毫秒,buff2离开范围是否移除buff0或1&quot;)(字符串，逗号和分号分割),<br/>参数6:触发器延时生成(整数单位ms,默认1),
        /// </summary>
        GenerateCollider = 6,
        /// <summary>
        /// 添加特效（临时特效用这个，常驻还是走buff）<br/>参数1:特效路径
        /// </summary>
        AddEffect = 7,
        /// <summary>
        /// 给自己加BUFF<br/>参数1:buffid,<br/>参数2时间ms
        /// </summary>
        AddBuff = 8,
        /// <summary>
        /// 移除自己BUFF<br/>参数1:buffid
        /// </summary>
        RemoveBuff = 9,
        /// <summary>
        ///  &lt;para&gt;改变Group&lt;/para&gt;&gt;<br/>&lt;para&gt;(1个参数.参数1:Group)&lt;/para&gt;&gt;<br/>&lt;para&gt;(2个参数.参数1:Condition 参数2:满足条件Group)&lt;/para&gt;&gt;<br/>&lt;para&gt;(3个参数.参数1:Condition 参数2:满足条件Group 参数3:不满足条件Group)&lt;/para&gt;&gt;
        /// </summary>
        ChangeGroup = 10,
    }

} 
