//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class AttributeConfig: Bright.Config.BeanBase
{
    public AttributeConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Remarks = _buf.ReadString();
        Key = _buf.ReadString();
        Name = _buf.ReadString();
        Type = _buf.ReadInt();
        Show = _buf.ReadInt();
        Affected = _buf.ReadInt();
        Desc = _buf.ReadString();
        PostInit();
    }

    public static AttributeConfig DeserializeAttributeConfig(ByteBuf _buf)
    {
        return new AttributeConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 策划备注(程序不读)
    /// </summary>
    public string Remarks { get; private set; }
    /// <summary>
    /// 索引
    /// </summary>
    public string Key { get; private set; }
    /// <summary>
    /// 名称
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 类型(0:整数,1:小数)
    /// </summary>
    public int Type { get; private set; }
    /// <summary>
    /// 显示
    /// </summary>
    public int Show { get; private set; }
    /// <summary>
    /// 是否被BUFF影响
    /// </summary>
    public int Affected { get; private set; }
    /// <summary>
    /// 描述
    /// </summary>
    public string Desc { get; private set; }

    public const int __ID__ = 1818455262;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Remarks:" + Remarks + ","
        + "Key:" + Key + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "Show:" + Show + ","
        + "Affected:" + Affected + ","
        + "Desc:" + Desc + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}