//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------


namespace ET
{ 
    public enum ColliderShape
    {
        /// <summary>
        /// 无
        /// </summary>
        None = 0,
        /// <summary>
        /// 矩形
        /// </summary>
        OBB = 1,
        /// <summary>
        /// 球形
        /// </summary>
        Sphere = 2,
    }

} 
