//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------
using Bright.Serialization;
using System.Collections.Generic;


namespace ET
{

public sealed partial class SkillConfig: Bright.Config.BeanBase
{
    public SkillConfig(ByteBuf _buf) 
    {
        Id = _buf.ReadInt();
        Name = _buf.ReadString();
        Type = _buf.ReadString();
        TargetSelect = _buf.ReadString();
        Cooldown = _buf.ReadFloat();
        Description = _buf.ReadString();
        DamageTarget = _buf.ReadString();
        Probability = _buf.ReadString();
        DamageType = _buf.ReadString();
        ValueFormula = _buf.ReadString();
        Effect1 = _buf.ReadString();
        Effect2 = _buf.ReadString();
        Effect3 = _buf.ReadString();
        PostInit();
    }

    public static SkillConfig DeserializeSkillConfig(ByteBuf _buf)
    {
        return new SkillConfig(_buf);
    }

    /// <summary>
    /// Id
    /// </summary>
    public int Id { get; private set; }
    /// <summary>
    /// 名字
    /// </summary>
    public string Name { get; private set; }
    /// <summary>
    /// 技能类型
    /// </summary>
    public string Type { get; private set; }
    /// <summary>
    /// 目标选择
    /// </summary>
    public string TargetSelect { get; private set; }
    /// <summary>
    /// 冷却时间
    /// </summary>
    public float Cooldown { get; private set; }
    /// <summary>
    /// 技能描述
    /// </summary>
    public string Description { get; private set; }
    /// <summary>
    /// 伤害作用对象
    /// </summary>
    public string DamageTarget { get; private set; }
    /// <summary>
    /// 伤害触发概率
    /// </summary>
    public string Probability { get; private set; }
    /// <summary>
    /// 伤害类型
    /// </summary>
    public string DamageType { get; private set; }
    /// <summary>
    /// 伤害取值
    /// </summary>
    public string ValueFormula { get; private set; }
    public string Effect1 { get; private set; }
    public string Effect2 { get; private set; }
    public string Effect3 { get; private set; }

    public const int __ID__ = -844226349;
    public override int GetTypeId() => __ID__;

    public  void Resolve(Dictionary<string, IConfigSingleton> _tables)
    {
        PostResolve();
    }

    public  void TranslateText(System.Func<string, string, string> translator)
    {
    }

    public override string ToString()
    {
        return "{ "
        + "Id:" + Id + ","
        + "Name:" + Name + ","
        + "Type:" + Type + ","
        + "TargetSelect:" + TargetSelect + ","
        + "Cooldown:" + Cooldown + ","
        + "Description:" + Description + ","
        + "DamageTarget:" + DamageTarget + ","
        + "Probability:" + Probability + ","
        + "DamageType:" + DamageType + ","
        + "ValueFormula:" + ValueFormula + ","
        + "Effect1:" + Effect1 + ","
        + "Effect2:" + Effect2 + ","
        + "Effect3:" + Effect3 + ","
        + "}";
    }
    
    partial void PostInit();
    partial void PostResolve();
}
}